name: LT
favicon: null
layout_spectrum: 0.81478958344087
typography_spectrum: 0.7640336544718593
title: LT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e7e5'
    - '#0c191f'
    - '#4b7bcf'
    - '#beb336'
    - '#a55d89'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
