name: LT
favicon: null
layout_spectrum: 0.81478958344087
typography_spectrum: 0.7640336544718593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21630053129047155
  lightness: 0.5411479221656919
  saturation: 0.26942275813780725
  rhythmicContrast: 0.06482319161295891
purpose: []
